In [1]:
import pandas as pd

# 5.1 Introduction to pandas Data Structures

# Series

Series é unidimensional contendo um array indexado 

In [2]:
obj = pd.Series([4, 5,-3, 0])
obj

0    4
1    5
2   -3
3    0
dtype: int64

In [3]:
obj.values

array([ 4,  5, -3,  0], dtype=int64)

In [4]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [5]:
obj2 = pd.Series([4, 5,-3, 0], index=['a', 'x', 'f', 'k'])
obj2

a    4
x    5
f   -3
k    0
dtype: int64

In [6]:
obj2.index

Index(['a', 'x', 'f', 'k'], dtype='object')

Selecionar os dados

In [7]:
obj2['k']

0

Tem como filtrar uma Series e como calcular

In [8]:
obj2[obj2 > 0]

a    4
x    5
dtype: int64

In [9]:
obj2 * 2

a     8
x    10
f    -6
k     0
dtype: int64

In [10]:
'b' in obj2

False

In [11]:
'k' in obj2

True

Como transformar um dicionário em uma series

In [12]:
data = {'Ohio' : 35000, 'Texas' : 71000, 'Oregon' : 16000, 'Utah' : 50000}
obj3 = pd.Series(data)
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah      50000
dtype: int64

In [13]:
states = ['California', 'Ohio', 'Oregon', 'Texas']
obj4 = pd.Series(data, index=states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

Verificar informações vazias 

In [14]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

Verificar informações que não estão vazias 

In [15]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

Verificar se tem os dados nas duas listas 

In [16]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

Dar nome a coluna do index e para a coluna dos dados

In [17]:
obj4.index.name = 'Estados'
obj4.name = 'Populacao'
obj4

Estados
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: Populacao, dtype: float64

In [18]:
obj

0    4
1    5
2   -3
3    0
dtype: int64

In [19]:
obj.index = ['Bob','Steve','Jeff','Ryan']
obj

Bob      4
Steve    5
Jeff    -3
Ryan     0
dtype: int64

# DataFrame

Pode ter mais de uma dimensão, pode conter vários tipos de dados

In [20]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'], 
       'year': [2000, 2001, 2002, 2001, 2002, 2003],
       'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [21]:
frame.head() #Seleciona as 5 primeiras linhas

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

Mudar a sequência das colunas

In [22]:
pd.DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [23]:
frame['state']

0      Ohio
1      Ohio
2      Ohio
3    Nevada
4    Nevada
5    Nevada
Name: state, dtype: object

In [24]:
frame.state

0      Ohio
1      Ohio
2      Ohio
3    Nevada
4    Nevada
5    Nevada
Name: state, dtype: object

loc -> localiza um index 

In [25]:
frame.loc[3]

state    Nevada
year       2001
pop         2.4
Name: 3, dtype: object

In [26]:
frame.index = ['zero','one', 'two','three', 'four', 'five']
frame

state  year  pop
zero     Ohio  2000  1.5
one      Ohio  2001  1.7
two      Ohio  2002  3.6
three  Nevada  2001  2.4
four   Nevada  2002  2.9
five   Nevada  2003  3.2

In [27]:
frame.loc['three']

state    Nevada
year       2001
pop         2.4
Name: three, dtype: object

In [28]:
frame = pd.DataFrame(frame, columns=['year', 'state', 'pop', 'debt'])
frame

year   state  pop  debt
zero   2000    Ohio  1.5   NaN
one    2001    Ohio  1.7   NaN
two    2002    Ohio  3.6   NaN
three  2001  Nevada  2.4   NaN
four   2002  Nevada  2.9   NaN
five   2003  Nevada  3.2   NaN

Adicionar dados em todas as linhas da coluna

In [29]:
frame['debt'] = 16.5 
frame

year   state  pop  debt
zero   2000    Ohio  1.5  16.5
one    2001    Ohio  1.7  16.5
two    2002    Ohio  3.6  16.5
three  2001  Nevada  2.4  16.5
four   2002  Nevada  2.9  16.5
five   2003  Nevada  3.2  16.5

In [30]:
import numpy as np

In [31]:
frame['debt'] = np.arange(6.)
frame

year   state  pop  debt
zero   2000    Ohio  1.5   0.0
one    2001    Ohio  1.7   1.0
two    2002    Ohio  3.6   2.0
three  2001  Nevada  2.4   3.0
four   2002  Nevada  2.9   4.0
five   2003  Nevada  3.2   5.0

Dá para atrelar uma Seriesna coluna debt 

In [32]:
debt = pd.Series([-1.2, -1.5, -1.7], index=['two','four','five'])
frame['debt'] = debt
frame

year   state  pop  debt
zero   2000    Ohio  1.5   NaN
one    2001    Ohio  1.7   NaN
two    2002    Ohio  3.6  -1.2
three  2001  Nevada  2.4   NaN
four   2002  Nevada  2.9  -1.5
five   2003  Nevada  3.2  -1.7

Adicionar mais uma coluna

In [33]:
frame['eastern'] = frame.state == 'Ohio'
frame

year   state  pop  debt  eastern
zero   2000    Ohio  1.5   NaN     True
one    2001    Ohio  1.7   NaN     True
two    2002    Ohio  3.6  -1.2     True
three  2001  Nevada  2.4   NaN    False
four   2002  Nevada  2.9  -1.5    False
five   2003  Nevada  3.2  -1.7    False

Como remover uma coluna 

In [34]:
del frame['eastern']
frame

year   state  pop  debt
zero   2000    Ohio  1.5   NaN
one    2001    Ohio  1.7   NaN
two    2002    Ohio  3.6  -1.2
three  2001  Nevada  2.4   NaN
four   2002  Nevada  2.9  -1.5
five   2003  Nevada  3.2  -1.7

In [35]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9}, 'Ohio': {2000: 1.5, 2001: 1.7, 2002:3.6}}
frame3 = pd.DataFrame(pop)
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

Invertendo a tabela 

In [36]:
frame3.T

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

Verificar se os dados que tem deacordo com o index 

In [37]:
pd.DataFrame(pop, index=[2001, 2002, 2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [38]:
pd.DataFrame(pop, index=[2011, 2012, 2001])

Nevada  Ohio
2011     NaN   NaN
2012     NaN   NaN
2001     2.4   1.7

In [39]:
pdata = {'Ohio': frame3['Ohio'] [:-1], 'Nevada': frame3['Nevada'][:2]}
pd.DataFrame(pdata)

Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9

In [40]:
frame3.index.name = 'year'
frame3.columns.name = 'state'
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [41]:
frame3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [42]:
frame

year   state  pop  debt
zero   2000    Ohio  1.5   NaN
one    2001    Ohio  1.7   NaN
two    2002    Ohio  3.6  -1.2
three  2001  Nevada  2.4   NaN
four   2002  Nevada  2.9  -1.5
five   2003  Nevada  3.2  -1.7

In [43]:
frame.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, nan],
       [2002, 'Ohio', 3.6, -1.2],
       [2001, 'Nevada', 2.4, nan],
       [2002, 'Nevada', 2.9, -1.5],
       [2003, 'Nevada', 3.2, -1.7]], dtype=object)

# Index Objects 

In [44]:
obj = pd.Series(range(3), index=['a', 'b', 'c'])
obj

a    0
b    1
c    2
dtype: int64

In [45]:
index = obj.index
index

Index(['a', 'b', 'c'], dtype='object')

In [46]:
index[1:]

Index(['b', 'c'], dtype='object')

Objetos de Index são imutáveis

In [47]:
labels = pd.Index(np.arange(3))
labels

Int64Index([0, 1, 2], dtype='int64')

In [48]:
obj2 = pd.Series([1.5, -2.5, 0], index=labels)
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [49]:
obj2.index is labels

True

Index com informação duplicada

In [50]:
dup_labels = pd.Index(['foo', 'foo', 'bar', 'bar','Teste'])
dup_labels

Index(['foo', 'foo', 'bar', 'bar', 'Teste'], dtype='object')

In [51]:
dup_labels2 = pd.Index(['foo', 'bar', 'bar', 'Teste_2'])
dup_labels2

Index(['foo', 'bar', 'bar', 'Teste_2'], dtype='object')

In [52]:
dup_labels.append(dup_labels2)

Index(['foo', 'foo', 'bar', 'bar', 'Teste', 'foo', 'bar', 'bar', 'Teste_2'], dtype='object')

In [53]:
dup_labels.difference(dup_labels2) #Mostra a diferença do primeiro index para o segundo

Index(['Teste'], dtype='object')

In [54]:
dup_labels.intersection(dup_labels2)

Index(['foo', 'bar'], dtype='object')

In [55]:
dup_labels.union(dup_labels2)

Index(['Teste', 'Teste_2', 'bar', 'bar', 'foo', 'foo'], dtype='object')

In [56]:
dup_labels.isin(dup_labels2)

array([ True,  True,  True,  True, False])

In [57]:
dup_labels.delete(1)

Index(['foo', 'bar', 'bar', 'Teste'], dtype='object')

In [58]:
dup_labels.drop('bar')

Index(['foo', 'foo', 'Teste'], dtype='object')

In [59]:
dup_labels.insert(0,'Casa')

Index(['Casa', 'foo', 'foo', 'bar', 'bar', 'Teste'], dtype='object')

In [60]:
dup_labels.is_monotonic #Return true if each element is greater than or equal to the previous element

False

In [61]:
dup_labels.is_unique # ferifica se tem elementos duplicados

False

In [62]:
dup_labels.unique(0) #Unifica os indices

Index(['foo', 'bar', 'Teste'], dtype='object')

# 5.2 Essential Functionality

Reindexing

In [63]:
import numpy as np
np.random.randint(0,15, 10)

array([13,  1,  2,  7,  0, 13,  8,  1, 13,  9])

In [64]:
obj = pd.Series(np.random.randint(0,15, 5), index='a b c d e'.split(' '))
obj

a     3
b    13
c     3
d     4
e     2
dtype: int32

In [65]:
obj2 = obj.reindex(index='d b c a e f g'.split(' ')) #Introduz index mas não muda os valores dos que tem 
obj2

d     4.0
b    13.0
c     3.0
a     3.0
e     2.0
f     NaN
g     NaN
dtype: float64

In [66]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 7])
obj3

0      blue
2    purple
7    yellow
dtype: object

In [67]:
obj3.reindex(range(10), method='ffill')

0      blue
1      blue
2    purple
3    purple
4    purple
5    purple
6    purple
7    yellow
8    yellow
9    yellow
dtype: object

In [68]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)), index=['a', 'c', 'd'], columns=['Ohio', 'Texas', 'California'])
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [69]:
frame2 = frame.reindex(['a', 'b', 'c', 'd'])
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [70]:
states = ['Texas', 'Ohio', 'California', 'Utha']
frame.reindex(columns=states)

Texas  Ohio  California  Utha
a      1     0           2   NaN
c      4     3           5   NaN
d      7     6           8   NaN

Dropping Entries from an Axis

In [71]:
obj = pd.Series(np.arange(5.),index=['a', 'b', 'c', 'd', 'e'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [72]:
new_obj = obj.drop('c')
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [73]:
obj.drop(['d', 'c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [74]:
data = pd.DataFrame(np.arange(16).reshape((4,4)), 
                   index = ['Ohio', 'Colorado', 'Utha', 'New York'],
                   columns = ['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utha        8    9     10    11
New York   12   13     14    15

In [75]:
data.drop(['Colorado', 'Ohio'])

one  two  three  four
Utha        8    9     10    11
New York   12   13     14    15

In [76]:
data.drop('two', axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utha        8     10    11
New York   12     14    15

In [77]:
data.drop(['two', 'four'], axis='columns') #outra forma de remover pela coluna

one  three
Ohio        0      2
Colorado    4      6
Utha        8     10
New York   12     14

In [78]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utha        8    9     10    11
New York   12   13     14    15

In [79]:
data.drop('Ohio', inplace=True) #remove a linha Ohio para sempre 
data

one  two  three  four
Colorado    4    5      6     7
Utha        8    9     10    11
New York   12   13     14    15

In [80]:
data

one  two  three  four
Colorado    4    5      6     7
Utha        8    9     10    11
New York   12   13     14    15

inplace destruirá qualquer dado para sempre

Indexação, Seleção e Filtragem

Fatiamento de Series

In [81]:
obj = pd.Series(np.arange(4.), index=('a b c d').split(' '))
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [82]:
obj['b']

1.0

In [83]:
obj[1]

1.0

In [84]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [85]:
obj[['b', 'c', 'a']]

b    1.0
c    2.0
a    0.0
dtype: float64

In [86]:
obj[[1, 3, 2]]

b    1.0
d    3.0
c    2.0
dtype: float64

In [87]:
obj[obj < 2]

a    0.0
b    1.0
dtype: float64

In [88]:
obj[['b', 'c', 'a']] = 5
obj

a    5.0
b    5.0
c    5.0
d    3.0
dtype: float64

Fatiamento de DataFrame

In [89]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                   index = ['Ohio', 'Colorado', 'Utha', 'New York'],
                   columns = ['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utha        8    9     10    11
New York   12   13     14    15

In [90]:
data['two']

Ohio         1
Colorado     5
Utha         9
New York    13
Name: two, dtype: int32

In [91]:
data['two']

Ohio         1
Colorado     5
Utha         9
New York    13
Name: two, dtype: int32

In [92]:
data.loc['Ohio']

one      0
two      1
three    2
four     3
Name: Ohio, dtype: int32

In [93]:
data[['two', 'one', 'four']]

two  one  four
Ohio        1    0     3
Colorado    5    4     7
Utha        9    8    11
New York   13   12    15

In [94]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [95]:
data[1:2]

one  two  three  four
Colorado    4    5      6     7

In [96]:
data[data['three']>5]

one  two  three  four
Colorado    4    5      6     7
Utha        8    9     10    11
New York   12   13     14    15

In [97]:
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utha      False  False  False  False
New York  False  False  False  False

In [98]:
data[data < 5] = 0
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utha        8    9     10    11
New York   12   13     14    15

Seleção com loc e iloc

Serve para filtrar por linha

In [99]:
data.loc['Colorado', ['two', 'three']]

two      5
three    6
Name: Colorado, dtype: int32

In [100]:
data.iloc[2, [3, 0, 1]]

four    11
one      8
two      9
Name: Utha, dtype: int32

In [101]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utha, dtype: int32

In [102]:
data.iloc[[1, 2], [3, 0, 1]]

four  one  two
Colorado     7    0    5
Utha        11    8    9

In [103]:
data.loc[:'Utha', 'two']

Ohio        0
Colorado    5
Utha        9
Name: two, dtype: int32

In [104]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utha        8    9     10    11
New York   12   13     14    15

In [105]:
data.iloc[:, :3]

one  two  three
Ohio        0    0      0
Colorado    0    5      6
Utha        8    9     10
New York   12   13     14

In [106]:
data.iloc[:, :3][data.three > 7]

one  two  three
Utha        8    9     10
New York   12   13     14

Aritmética e alinhamento de dados

In [107]:
s1 = pd.Series(np.random.randint(0,15, 5), index='a b c d e'.split(' '))
s1

a    14
b    11
c     0
d     9
e     3
dtype: int32

In [108]:
s2 = pd.Series(np.random.randint(0,15, 5), index='a c f x e'.split(' '))
s2

a    14
c    14
f     3
x     3
e    11
dtype: int32

In [109]:
s1 + s2

a    28.0
b     NaN
c    14.0
d     NaN
e    14.0
f     NaN
x     NaN
dtype: float64

In [110]:
np.random.randint(0, 15, [3,3])

array([[ 4, 14,  4],
       [ 8, 13, 10],
       [ 0, 10, 11]])

In [111]:
np.arange(9.).reshape((3,3))

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [112]:
s1 = pd.DataFrame(np.random.randint(0, 15, [3,3]), columns=list('bcd'), index=['Ohio', 'Colorado', 'Utha'])
s1

b   c   d
Ohio      13  13  11
Colorado  11   6   6
Utha      11  13  11

In [113]:
s2 = pd.DataFrame(np.random.randint(0, 15, [4,3]), columns=list('bde'), index=['Ohio', 'Colorado', 'Utha', 'Oregon'])
s2

b   d   e
Ohio      14   7  10
Colorado  10   1   4
Utha       9  13  12
Oregon     9   7  14

In [114]:
s1 + s2

b   c     d   e
Colorado  21.0 NaN   7.0 NaN
Ohio      27.0 NaN  18.0 NaN
Oregon     NaN NaN   NaN NaN
Utha      20.0 NaN  24.0 NaN

Se somar objetos DataFrame sem rótulos para colunas ou linhas em comum, o resultado conterá somente nulos

In [115]:
df1 = pd.DataFrame({'A': [1, 2]})
df1

A
0  1
1  2

In [116]:
df2 = pd.DataFrame({'B': [1, 2]})
df2

B
0  1
1  2

In [117]:
df1 + df2

A   B
0 NaN NaN
1 NaN NaN

Métodos Aritméticos com valores para preenchimento

In [118]:
s1 = pd.DataFrame(np.random.randint(3, 35, [3,4]), columns=list('abcd'))
s1

a   b   c   d
0  25   5  18  17
1  18  26  30   5
2  24  28  12  28

In [119]:
s2 = pd.DataFrame(np.random.randint(3, 35, [4, 5]), columns=list('abcde'))
s2

a   b   c   d   e
0  13  11  23  24   6
1  34  16  31  15  24
2  18  28   8   9  15
3  22  31  30  17  24

In [120]:
s2.loc[1, 'b'] = np.nan
s2

a     b   c   d   e
0  13  11.0  23  24   6
1  34   NaN  31  15  24
2  18  28.0   8   9  15
3  22  31.0  30  17  24

In [121]:
s1 + s2

a     b     c     d   e
0  38.0  16.0  41.0  41.0 NaN
1  52.0   NaN  61.0  20.0 NaN
2  42.0  56.0  20.0  37.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [122]:
s1

a   b   c   d
0  25   5  18  17
1  18  26  30   5
2  24  28  12  28

In [123]:
s1.add(s2, fill_value=0) #Preenche os espaços com os dados de s2

a     b     c     d     e
0  38.0  16.0  41.0  41.0   6.0
1  52.0  26.0  61.0  20.0  24.0
2  42.0  56.0  20.0  37.0  15.0
3  22.0  31.0  30.0  17.0  24.0

In [124]:
1 / s1

a         b         c         d
0  0.040000  0.200000  0.055556  0.058824
1  0.055556  0.038462  0.033333  0.200000
2  0.041667  0.035714  0.083333  0.035714

In [125]:
s1.rdiv(1)

a         b         c         d
0  0.040000  0.200000  0.055556  0.058824
1  0.055556  0.038462  0.033333  0.200000
2  0.041667  0.035714  0.083333  0.035714

In [126]:
s1.reindex(columns=s2.columns, fill_value=0)

a   b   c   d  e
0  25   5  18  17  0
1  18  26  30   5  0
2  24  28  12  28  0

Operações entre DataFrame e Series

In [127]:
arr = np.arange(12.).reshape((3, 4))
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [128]:
arr[0]

array([0., 1., 2., 3.])

In [129]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

Quando subtraímos arr[0] de arr, a subtração é realizada uma vez para cada linha. Isso é chamado de broadcasting

In [130]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'), index=['Ohio', 'Colorado', 'Utha', 'Oregon'])
frame

b     d     e
Ohio      0.0   1.0   2.0
Colorado  3.0   4.0   5.0
Utha      6.0   7.0   8.0
Oregon    9.0  10.0  11.0

In [131]:
series = frame.iloc[1]
series

b    3.0
d    4.0
e    5.0
Name: Colorado, dtype: float64

In [132]:
frame - series #Por padrão, a aritmética entre DataFrame e Series realiza a correspondência entre o índice da Series 
                #e as colunas do DataFrame, fazendo broadcasting pelas linhas

b    d    e
Ohio     -3.0 -3.0 -3.0
Colorado  0.0  0.0  0.0
Utha      3.0  3.0  3.0
Oregon    6.0  6.0  6.0

In [133]:
series2 = pd.Series(range(3), index=['b', 'e', 'f'])
series2

b    0
e    1
f    2
dtype: int64

In [134]:
frame

b     d     e
Ohio      0.0   1.0   2.0
Colorado  3.0   4.0   5.0
Utha      6.0   7.0   8.0
Oregon    9.0  10.0  11.0

In [135]:
frame + series2

b   d     e   f
Ohio      0.0 NaN   3.0 NaN
Colorado  3.0 NaN   6.0 NaN
Utha      6.0 NaN   9.0 NaN
Oregon    9.0 NaN  12.0 NaN

In [136]:
series3 = frame['d']
series3

Ohio         1.0
Colorado     4.0
Utha         7.0
Oregon      10.0
Name: d, dtype: float64

In [137]:
frame.sub(series3, axis='index')

b    d    e
Ohio     -1.0  0.0  1.0
Colorado -1.0  0.0  1.0
Utha     -1.0  0.0  1.0
Oregon   -1.0  0.0  1.0

Aplicação de Funções e Mapeamento

In [138]:
frame = pd.DataFrame(np.random.randn(4, 3), columns=list('bde'), index=['Ohio', 'Colorado', 'Utha', 'Oregon'])
frame

b         d         e
Ohio     -0.019312 -1.365907  0.967324
Colorado -0.165734 -0.408766  0.675353
Utha     -0.478192 -0.808950  0.858684
Oregon    0.934727  1.899241  0.701546

In [139]:
np.abs(frame) #deixa todo mundo positivo

b         d         e
Ohio      0.019312  1.365907  0.967324
Colorado  0.165734  0.408766  0.675353
Utha      0.478192  0.808950  0.858684
Oregon    0.934727  1.899241  0.701546

In [140]:
f = lambda x: x.max() - x.min() #Subtrai o maior número com o menor da coluna 
frame.apply(f)

b    1.412920
d    3.265149
e    0.291971
dtype: float64

In [141]:
frame.apply(f, axis='columns') #Subtrai o maior número com o menor da linha

Ohio        2.333231
Colorado    1.084118
Utha        1.667634
Oregon      1.197695
dtype: float64

In [142]:
def f(x):
    return pd.Series([x.min(), x.max()], index=['min', 'max'])
frame.apply(f)

b         d         e
min -0.478192 -1.365907  0.675353
max  0.934727  1.899241  0.967324

In [143]:
f = lambda x: '%.2f' % x 
frame.applymap(f)

b      d     e
Ohio      -0.02  -1.37  0.97
Colorado  -0.17  -0.41  0.68
Utha      -0.48  -0.81  0.86
Oregon     0.93   1.90  0.70

In [144]:
frame['e'].map(f)

Ohio        0.97
Colorado    0.68
Utha        0.86
Oregon      0.70
Name: e, dtype: object

Ordenação e classificação

In [145]:
obj = pd.Series(range(4), index=list('dabc'))
obj

d    0
a    1
b    2
c    3
dtype: int64

In [146]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [147]:
frame = pd.DataFrame(np.arange(8).reshape((2, 4)), 
                    index=['three', 'one'],
                    columns = list('dabc'))
frame

d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [148]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [149]:
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

Ordenação de forma decrescente

In [150]:
frame.sort_index(axis=1, ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [151]:
obj = pd.Series(np.random.randint(1, 100, 10))
obj

0    49
1    16
2     9
3     4
4    81
5    80
6    15
7    74
8    62
9    90
dtype: int32

In [152]:
obj.sort_values()

3     4
2     9
6    15
1    16
0    49
8    62
7    74
5    80
4    81
9    90
dtype: int32

In [153]:
obj[9, 3, 5] = np.nan
obj

0    49.0
1    16.0
2     9.0
3     NaN
4    81.0
5     NaN
6    15.0
7    74.0
8    62.0
9     NaN
dtype: float64

In [154]:
obj.sort_values() #Valores vazios ficam por último

2     9.0
6    15.0
1    16.0
0    49.0
8    62.0
7    74.0
4    81.0
3     NaN
5     NaN
9     NaN
dtype: float64

In [155]:
frame = pd.DataFrame(np.random.randint(1, 100, [10, 4]), columns=list('abcd'))
frame

a   b   c   d
0  44  21  21   7
1  88  76  55  16
2  69  20  40  23
3  58  31  73  28
4  79  32   8  21
5  85  73  67  44
6   1  11  14  82
7  39  17  61  35
8  26  45  95  78
9  44  26  99  79

In [156]:
frame.sort_values(by='b')

a   b   c   d
6   1  11  14  82
7  39  17  61  35
2  69  20  40  23
0  44  21  21   7
9  44  26  99  79
3  58  31  73  28
4  79  32   8  21
8  26  45  95  78
5  85  73  67  44
1  88  76  55  16

In [157]:
frame.loc[0] = [0, 4, 4, 9]
frame.loc[5] = [0, 4, 3, 9]
frame

a   b   c   d
0   0   4   4   9
1  88  76  55  16
2  69  20  40  23
3  58  31  73  28
4  79  32   8  21
5   0   4   3   9
6   1  11  14  82
7  39  17  61  35
8  26  45  95  78
9  44  26  99  79

In [158]:
frame.sort_values(by=['b', 'c']) #Faz o sequência em 'b' e desempata em 'C'

a   b   c   d
5   0   4   3   9
0   0   4   4   9
6   1  11  14  82
7  39  17  61  35
2  69  20  40  23
9  44  26  99  79
3  58  31  73  28
4  79  32   8  21
8  26  45  95  78
1  88  76  55  16

In [159]:
obj = pd.Series(np.random.randint(-10, 10, 10))
obj

0    0
1    1
2    9
3    0
4    0
5    2
6    1
7    9
8    0
9   -5
dtype: int32

In [160]:
obj.rank()

0    3.5
1    6.5
2    9.5
3    3.5
4    3.5
5    8.0
6    6.5
7    9.5
8    3.5
9    1.0
dtype: float64

In [161]:
obj.rank(method='first')

0     2.0
1     6.0
2     9.0
3     3.0
4     4.0
5     8.0
6     7.0
7    10.0
8     5.0
9     1.0
dtype: float64

In [162]:
obj.rank(ascending=False, method='max')

0     9.0
1     5.0
2     2.0
3     9.0
4     9.0
5     3.0
6     5.0
7     2.0
8     9.0
9    10.0
dtype: float64

In [163]:
frame = pd.DataFrame(np.random.randint(-100, 100, [10, 4]), columns=list('abcd'))
frame

a   b   c   d
0 -22  90  53  69
1 -14 -42 -96  51
2 -83  95 -38 -39
3 -99 -62  95  51
4  13  42  92  83
5 -12  -9 -63  -5
6  12  86 -83 -33
7  12  28 -14 -60
8 -56 -73  97 -90
9 -27 -17 -85  19

In [164]:
frame.rank(axis='columns')

a    b    c    d
0  1.0  4.0  2.0  3.0
1  3.0  2.0  1.0  4.0
2  1.0  4.0  3.0  2.0
3  1.0  2.0  4.0  3.0
4  1.0  2.0  4.0  3.0
5  2.0  3.0  1.0  4.0
6  3.0  4.0  1.0  2.0
7  3.0  4.0  2.0  1.0
8  3.0  2.0  4.0  1.0
9  2.0  3.0  1.0  4.0

Índices de eixos com rótulos duplicados

In [165]:
obj = pd.Series(range(5), index=list('aabbc'))
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [166]:
obj.index.is_unique

False

In [167]:
obj['a']

a    0
a    1
dtype: int64

In [168]:
frame = pd.DataFrame(np.random.randint(-100, 100, [5, 4]), index=list('aabbc'), columns=list('0123'))
frame

0   1   2   3
a -39 -69 -64  53
a  25  59 -32  93
b -26 -52  98 -89
b   5  18  91 -68
c -62 -18 -52  52

In [169]:
frame.loc['a']

0   1   2   3
a -39 -69 -64  53
a  25  59 -32  93

# 5.3 Resumindo e calculando estatística descritivas

Reduções ou estatística de resumo: são métodos que extraem um único valor(como a soma ou a média) de uma Series ou uma Series de valores das linhas ou colunas de um Data Frame. Em comparação com métodos similares que se encontram em arraus NumPu, eles têm tratamento embutido para dados ausentes

In [170]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5],
                  [np.nan, np.nan], [0.75, -1.3]],
                 index = list('abcd'),
                 columns=['one', 'two'])
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [171]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [172]:
df.sum(axis='columns')

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [173]:
df.mean(axis='columns')

a    1.400
b    1.300
c      NaN
d   -0.275
dtype: float64

In [174]:
df.mean(axis='columns', skipna=False) #skipna não calcula os valores NaN

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [175]:
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [176]:
df.idxmax() #retorna o indice que os valores mínimo e máximo são encontrados

one    b
two    d
dtype: object

In [177]:
df.idxmin()

one    d
two    b
dtype: object

In [178]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [179]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [180]:
obj = pd.Series(['a', 'a', 'b', 'c']*4)
obj

0     a
1     a
2     b
3     c
4     a
5     a
6     b
7     c
8     a
9     a
10    b
11    c
12    a
13    a
14    b
15    c
dtype: object

In [181]:
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

Correlação e Covariância

In [182]:
import pandas_datareader.data as web

O módulo pandas_datareader é utilizado para fazer download de alguns dados de algumas listas de ações

In [183]:
all_data = {ticker: web.get_data_yahoo(ticker) for ticker in ['AAPL', 'IBM', 'MSFT', 'GOOG']}

In [184]:
price = pd.DataFrame({ticker: data['Adj Close'] for ticker, data in all_data.items()})
price

AAPL         IBM        MSFT         GOOG
Date                                                       
2016-09-14   26.205605  122.996796   52.053368   762.489990
2016-09-15   27.096560  124.282288   52.913830   771.760010
2016-09-16   26.944162  122.829163   52.969353   768.880005
2016-09-19   26.629980  123.651497   52.673271   765.700012
2016-09-20   26.627634  123.316193   52.562248   771.409973
...                ...         ...         ...          ...
2021-09-07  156.690002  138.059998  300.179993  2910.379883
2021-09-08  155.110001  138.669998  300.209991  2897.669922
2021-09-09  154.070007  137.740005  297.250000  2898.270020
2021-09-10  148.970001  137.020004  295.709991  2838.419922
2021-09-13  149.439896  137.910004  295.390015  2848.860107

[1258 rows x 4 columns]

In [185]:
volume = pd.DataFrame({ticker: data['Volume'] for ticker, data in all_data.items()})
volume

AAPL        IBM        MSFT     GOOG
Date                                                   
2016-09-14  443554800.0  3860600.0  24062500.0  1087400
2016-09-15  359934400.0  3645600.0  26847000.0  1305100
2016-09-16  319547600.0  6463600.0  44607000.0  2049300
2016-09-19  188092000.0  2450100.0  20937100.0  1172800
2016-09-20  138057200.0  2159100.0  17384000.0   978600
...                 ...        ...         ...      ...
2021-09-07   82278300.0  3285000.0  17180400.0   758500
2021-09-08   74420200.0  2985400.0  15046800.0   774300
2021-09-09   57305700.0  3508300.0  19927000.0   739900
2021-09-10  140646400.0  3974100.0  19619400.0  1643500
2021-09-13   25398849.0   568808.0   3866473.0   273165

[1258 rows x 4 columns]

In [186]:
returns = price.pct_change() #calcula as mudanças percentuais nos preços 
returns.tail()

AAPL       IBM      MSFT      GOOG
Date                                              
2021-09-07  0.015489 -0.010890 -0.003188  0.005139
2021-09-08 -0.010084  0.004418  0.000100 -0.004367
2021-09-09 -0.006705 -0.006707 -0.009860  0.000207
2021-09-10 -0.033102 -0.005227 -0.005181 -0.020650
2021-09-13  0.003154  0.006495 -0.001082  0.003678

In [187]:
returns['MSFT'].corr(returns['IBM']) 
#Calcula a correlação entre os valores de diferentes de NA de duas Series, alinhados pelo índice e que se sobrepõem.
#De forma relacionada

0.5152606029103067

In [188]:
returns['MSFT'].cov(returns['IBM'])# Calcula a covariância

0.00014470050428794711

In [189]:
returns.corr()

AAPL       IBM      MSFT      GOOG
AAPL  1.000000  0.441415  0.736603  0.663213
IBM   0.441415  1.000000  0.515261  0.482308
MSFT  0.736603  0.515261  1.000000  0.773781
GOOG  0.663213  0.482308  0.773781  1.000000

In [190]:
returns.cov()

AAPL       IBM      MSFT      GOOG
AAPL  0.000361  0.000137  0.000240  0.000212
IBM   0.000137  0.000267  0.000145  0.000133
MSFT  0.000240  0.000145  0.000295  0.000224
GOOG  0.000212  0.000133  0.000224  0.000283

In [191]:
returns.corrwith(returns.IBM) #Calcula a correlação de pares entre colunas ou linhas de um DataFrame

AAPL    0.441415
IBM     1.000000
MSFT    0.515261
GOOG    0.482308
dtype: float64

In [192]:
returns.corrwith(volume)

AAPL   -0.072874
IBM    -0.103722
MSFT   -0.054099
GOOG   -0.120569
dtype: float64

Valores únicos, contadores de valores e pertinência

In [193]:
obj = pd.Series(list('cadaabbcc'))
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [194]:
uniques = obj.unique()
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [195]:
obj.value_counts()

a    3
c    3
b    2
d    1
dtype: int64

In [196]:
pd.value_counts(obj.values, sort=False)

a    3
d    1
c    3
b    2
dtype: int64

In [197]:
mask=obj.isin(['b','c']) #Verifica se contem esse dado
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [198]:
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

In [199]:
to_match = pd.Series(list('cabbca'))
unique_vals = pd.Series(list('cba'))

In [200]:
pd.Index(unique_vals).get_indexer(to_match)

array([0, 2, 1, 1, 0, 2], dtype=int64)

In [201]:
data = pd.DataFrame(np.random.randint(1, 5, [5, 3]), columns=['Qu1', 'Qu2', 'Qu3'])
data

Qu1  Qu2  Qu3
0    1    4    2
1    4    1    3
2    4    4    3
3    3    2    3
4    4    4    2

In [202]:
result = data.apply(pd.value_counts).fillna(0)
result

Qu1  Qu2  Qu3
1  1.0  1.0  0.0
2  0.0  1.0  2.0
3  1.0  0.0  3.0
4  3.0  3.0  0.0

Os rótulos das linhas no resultado são os valores distintos que ocorrem em todas as colunas. Os valores são os respectivos contadores desses valores em cada coluna